### ISSUE TITLE
Is it possible to add this to a git repository?

### ISSUE THREAD

**Issue by eggbean** [redraw/gh-install#4]
Hi. This is the first gh extension I have used. I thought I would add it to my dotfiles repository so that I would automatically have it on all hosts. But I got the warning saying that it was a git repository itself.

Is there a way to add it to a synced git repository while still being able to update it using `gh extension upgrade` or do I have to remember to install extensions manually on each host?

**Comment by redraw** [comment]
@eggbean hi! sorry for the delay, just read. I guess that if you clone the repo into `$HOME/.local/share/gh/extensions/` that should work. I understand that Github CLI clones it there, and uses git to know when to upgrade.

**Comment by redraw** [comment]
actually @eggbean if I understand correctly, if your dotfiles is a git repo already, a good option would be to add this repo [as a git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) in the path from above

**Comment by eggbean** [comment]
Looks like submodules is a really useful thing to know about. Thanks.
